In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install numpy

In [1]:
import numpy as np

In [2]:
a =np.array([1,2,3])
print(a)


[1 2 3]


In [3]:
b = np.array([[.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[0. 8. 7.]
 [6. 5. 4.]]


In [5]:
# get dimension
b.ndim

2

In [7]:
# get shape
b.shape

(2, 3)

In [8]:
# get type
a.dtype

dtype('int32')

In [9]:
# get size
a.itemsize

4

In [10]:
# get total size
a.size* a.itemsize

12

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# get a specific element [r,c]
a[1,5]

13

In [15]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# get a specific column
a[:, 2]

array([ 3, 10])

In [18]:
# getting a little more fancy [startindex:endindex:stepindex]
a [0, 1:6:2]

array([2, 4, 6])

In [20]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [37]:
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [38]:
# get a specific element (work outside in)
b[:,1,1]

array([4])

In [33]:
# replace
b[:,1,:]

array([[3, 4]])

In [41]:
# All 0s matrix
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [42]:
# all 1s matrix
np.ones((4,2,2)), dtype='int32')

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [45]:
# any other number
np.full((2,2), 89)

array([[89, 89],
       [89, 89]])

In [48]:
# any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [51]:
# random decimal numbers
np.random.random_sample(a.shape)

array([[0.45275561, 0.78784997, 0.22021068, 0.72740767, 0.76385295,
        0.93845406, 0.48781717],
       [0.87028185, 0.65211372, 0.35166647, 0.48540362, 0.2893657 ,
        0.52715997, 0.69964328]])

In [54]:
# random integer values
np.random.randint(-4,8, size=(3,3))

array([[-2,  7, -2],
       [ 3,  1, -4],
       [ 0, -2,  7]])

In [56]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [63]:
output= np.ones([5,5])
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### be careful when copying arrays!!!

In [67]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


mathematics

In [68]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [69]:
a + 2

array([3, 4, 5, 6])

In [70]:
a - 2

array([-1,  0,  1,  2])

In [71]:
a * 2

array([2, 4, 6, 8])

In [72]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [74]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [75]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [77]:
# take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### linear algebra

In [80]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [81]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### statistics

In [82]:
stats = np.array([[1,2,3],[4,5,6,]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.min(stats)

1

In [86]:
np.max(stats, axis=1)

array([3, 6])

In [88]:
np.sum(stats, axis=0)

array([5, 7, 9])

## reorganizing arrays

In [90]:
before = np.array([[1,2,3,4,],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [91]:
# vertically stacking vectores
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [92]:
# horizontal stack
h1 = np.ones([2,4])
h2 = np.zeros([2,2])

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### miscellaneous

load data from file

##### boolean masking and advanced indexing